plugins {
    id 'java'
}

group = 'dev.kairos'
version = '0.1.0-SNAPSHOT'

ext {
    javaToolchainVersion = 26

    junitBomVersion = '5.11.4'
    testcontainersBomVersion = '1.20.4'
    flywayVersion = '11.1.1'
    postgresDriverVersion = '42.7.4'
}

subprojects {
    apply plugin: 'java'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(javaToolchainVersion)
        }
    }

    repositories {
        mavenCentral()
    }
}
