
#Project
group=dev.kairos
version=0.1.0-SNAPSHOT
javaToolchainVersion=26

#Plugins
studerJooqVersion=10.1

# Core
hikariVersion=7.1.0
jooqVersion=3.19.22
javalinVersion=6.4.0
jacksonVersion=2.18.2

#Database
flywayVersion=12.9.0
postgresDriverVersion=42.7.11

#Testing
junitBomVersion=5.11.4
testcontainersBomVersion=1.20.4
h2Version=2.3.232


#Logging
slf4jVersion=2.0.17
logbackVersion=1.5.18