description = 'Kairos REST API (entry point)'

// ── Dependencies ───────────────────────────────────────────────────────────────
dependencies {
    implementation project(':common')
    implementation project(':kairos-persistence')

    implementation "io.javalin:javalin:${javalinVersion}"

    implementation "org.slf4j:slf4j-api:${slf4jVersion}"
    runtimeOnly "ch.qos.logback:logback-classic:${logbackVersion}"

    testImplementation platform("org.junit:junit-bom:${junitBomVersion}")

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation "com.h2database:h2:${h2Version}"

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}
